# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:8080"
    links:
      - mongo
    environment:
        TZ: "America/Toronto"
        command: >
          sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
          echo $TZ > /etc/timezone"
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data
    ports:
      - "27017:27017"