# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data
    ports:
      - "27017:27017"